[system]
name = "BustAKrist"
listenPort = 8081

[game]
salt = "00000000000000000004bac129769598d1fad2b42859e625729661a32b9c3e71"
roundDelay = 3 # Seconds (showing the bust of the last round)
roundPadding = 5 # Seconds (before a round starts)
history = 40

[chat]
history = 40

[profile]
pageSize = 50
