[system]
name = "BustAKrist"
listenPort = 8081
logLevel = "silly"
chainFile = "devchain.txt"

[krist]
node = "krist.ceriat.net"
connectionBounce = 30

pkey = "60460870c906e8b01372063a3b03734de60d1a1a23fe1a6b467d99ff181c0bf9c"
address = "kitsemmaya"
names = ["bust", "bustakrist", "bak"]

[game]
salt = "00000000000000000004bac129769598d1fad2b42859e625729661a32b9c3e71"
roundDelay = 3 # Seconds (showing the bust of the last round)
roundPadding = 5 # Seconds (before a round starts)
history = 40

safetySingle = 0.15
safetyRound  = 0.3

[chat]
history = 40

[profile]
pageSize = 50
