[system]
name = "BustAKrist"
listenPort = 8081
logLevel = "silly"
chainFile = "devchain.txt"

[krist]
node = "krist.ceriat.net"
connectionBounce = 30

pkey = "df08db7a93fc4b53c3fbbe52c80daa0bce7fcc4c2f5017a0fd5bc568eb60fbf8-000"
address = "kitsemmaya"
names = ["bust", "bustakrist", "bak"]

[game]
salt = "00000000000000000004bac129769598d1fad2b42859e625729661a32b9c3e71"
roundDelay = 3 # Seconds (showing the bust of the last round)
roundPadding = 5 # Seconds (before a round starts)
history = 40

safetySingle = 0.15
safetyRound  = 0.3

[chat]
history = 40

[profile]
pageSize = 50
