[system]
name = "BustAKrist"
listenPort = 8457
metricsPort = 8458
logLevel = "info"
chainFile = "chain.txt"
webhook = "<<REDACTED>>"
exceptionsWebhook = "<<REDACTED>>"

[krist]
node = "krist.ceriat.net"
connectionBounce = 30

pkey = "<<REDACTED>>"
address = "kitsemmaya"
names = ["bust", "bustakrist", "bak"]

[game]
salt = "00000000000000000004bac129769598d1fad2b42859e625729661a32b9c3e71"
roundDelay = 3 # Seconds (showing the bust of the last round)
roundPadding = 5 # Seconds (before a round starts)
history = 40

safetySingle = 0.15
safetyRound  = 0.3

[chat]
history = 40

[profile]
pageSize = 50
